spring:
  application:
    name: spring-openai-demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javatechie
    username: root
    password: password

  ai:
    model:
      chat: ollama
      embedding: ollama
    ollama:
      chat:
        model: llama3.2
      embedding:
        model: nomic-embed-text
    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: javatechie

  docker:
    compose:
      stop:
        command: DOWN

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

server:
  port: 9292